const ACME_DUMMY_LEADS = [
  {
    customerName: 'Sarah Chen',
    email: 'sarah.chen@dummy-lead.example',
    subject: 'Enterprise software inquiry',
    phone: '+1 555-0101',
    followUpDate: '2026-07-15',
    score: 9,
    quality: 'high',
    pipelineName: 'Sales',
    stageName: 'Open',
    sourceSlugs: ['website-contact-form', 'linkedin-outreach'],
    notes: '<p>Interested in annual subscription. Requested demo next week.</p>',
  },
  {
    customerName: 'Marcus Webb',
    email: 'marcus.webb@dummy-lead.example',
    subject: 'Pricing for 50-seat plan',
    phone: '+1 555-0102',
    followUpDate: '2026-07-08',
    score: 7,
    quality: 'high',
    pipelineName: 'Sales',
    stageName: 'Sent',
    sourceSlugs: ['google-ads-campaign'],
    notes: '<p>Comparing vendors. Follow up with proposal.</p>',
  },
  {
    customerName: 'Elena Rodriguez',
    email: 'elena.rodriguez@dummy-lead.example',
    subject: 'Marketing automation integration',
    phone: '+1 555-0103',
    followUpDate: '2026-07-20',
    score: 6,
    quality: 'medium',
    pipelineName: 'Marketing',
    stageName: 'Engaged',
    sourceSlugs: ['email-marketing', 'content-marketing'],
    notes: null,
  },
  {
    customerName: 'James Okonkwo',
    email: 'james.okonkwo@dummy-lead.example',
    subject: 'Referral from partner network',
    phone: '+1 555-0104',
    followUpDate: '2026-07-12',
    score: 8,
    quality: 'high',
    pipelineName: 'Sales',
    stageName: 'Revised',
    sourceSlugs: ['partner-referral', 'referral-program'],
    notes: '<p>Warm intro from TechPartners Inc.</p>',
  },
  {
    customerName: 'Priya Sharma',
    email: 'priya.sharma@dummy-lead.example',
    subject: 'Trade show follow-up',
    phone: '+1 555-0105',
    followUpDate: '2026-06-30',
    score: 5,
    quality: 'medium',
    pipelineName: 'Lead Qualification',
    stageName: 'In Review',
    sourceSlugs: ['trade-show-events'],
    notes: '<p>Met at SaaS Summit. Needs qualification call.</p>',
  },
  {
    customerName: 'David Kim',
    email: 'david.kim@dummy-lead.example',
    subject: 'Cold outreach response',
    phone: null,
    followUpDate: '2026-07-05',
    score: 4,
    quality: 'low',
    pipelineName: 'Sales',
    stageName: 'Draft',
    sourceSlugs: ['cold-calling'],
    notes: null,
  },
  {
    customerName: 'Amanda Foster',
    email: 'amanda.foster@dummy-lead.example',
    subject: 'Webinar attendee — product tour',
    phone: '+1 555-0107',
    followUpDate: '2026-07-18',
    score: 7,
    quality: 'medium',
    pipelineName: 'Marketing',
    stageName: 'Qualified',
    sourceSlugs: ['webinar-registration', 'seo-organic-search'],
    notes: '<p>Asked about API access during Q&amp;A.</p>',
  },
  {
    customerName: 'Robert Hayes',
    email: 'robert.hayes@dummy-lead.example',
    subject: 'RFP submission deadline',
    phone: '+1 555-0108',
    followUpDate: '2026-07-02',
    score: 10,
    quality: 'high',
    pipelineName: 'Sales',
    stageName: 'Accepted',
    sourceSlugs: ['industry-publication', 'direct-mail-campaign'],
    notes: '<p>Decision expected by end of month.</p>',
  },
  {
    customerName: 'Nina Patel',
    email: 'nina.patel@dummy-lead.example',
    subject: 'Budget approval pending',
    phone: '+1 555-0109',
    followUpDate: '2026-07-22',
    score: 3,
    quality: 'low',
    pipelineName: 'Sales',
    stageName: 'Declined',
    sourceSlugs: ['social-media-marketing'],
    notes: '<p>Requested to reconnect in Q4.</p>',
  },
  {
    customerName: 'Thomas Wright',
    email: 'thomas.wright@dummy-lead.example',
    subject: 'Inbound demo request',
    phone: '+1 555-0110',
    followUpDate: '2026-07-10',
    score: 6,
    quality: 'medium',
    pipelineName: 'Lead Qualification',
    stageName: 'Unqualified',
    sourceSlugs: ['website-contact-form', 'seo-organic-search'],
    notes: null,
  },
  {
    customerName: 'Olivia Martinez',
    email: 'olivia.martinez@dummy-lead.example',
    subject: 'Newsletter signup — product interest',
    phone: null,
    followUpDate: '2026-07-25',
    score: 5,
    quality: 'medium',
    pipelineName: 'Marketing',
    stageName: 'Contacted',
    sourceSlugs: ['email-marketing', 'content-marketing'],
    notes: '<p>Downloaded whitepaper on CRM automation.</p>',
  },
  {
    customerName: 'Kevin O\'Brien',
    email: 'kevin.obrien@dummy-lead.example',
    subject: 'Multi-location rollout quote',
    phone: '+1 555-0112',
    followUpDate: '2026-07-14',
    score: 8,
    quality: 'high',
    pipelineName: 'Lead Qualification',
    stageName: 'Approved',
    sourceSlugs: ['partner-referral'],
    notes: '<p>Needs pricing for 12 locations.</p>',
  },
  {
    customerName: 'Hannah Lee',
    email: 'hannah.lee@dummy-lead.example',
    subject: 'Support plan upgrade inquiry',
    phone: '+1 555-0113',
    followUpDate: '2026-06-28',
    score: 7,
    quality: 'medium',
    pipelineName: 'Marketing',
    stageName: 'Prospect',
    sourceSlugs: ['webinar-registration'],
    notes: null,
  },
  {
    customerName: 'Michael Torres',
    email: 'michael.torres@dummy-lead.example',
    subject: 'Annual contract renewal discussion',
    phone: '+1 555-0114',
    followUpDate: '2026-07-30',
    score: 9,
    quality: 'high',
    pipelineName: 'Lead Qualification',
    stageName: 'Qualified',
    sourceSlugs: ['referral-program', 'direct-mail-campaign'],
    notes: '<p>Existing customer evaluating tier upgrade.</p>',
  },
];

module.exports = {
  ACME_DUMMY_LEADS,
};
