const ACME_DUMMY_LEADS = [
  {
    customerName: 'Sarah Chen',
    email: 'sarah.chen@dummy-lead.example',
    subject: 'Enterprise software inquiry',
    phone: '+1 555-0101',
    followUpDate: '2026-07-15',
    score: 9,
    quality: 'high',
    pipelineName: 'Sales',
    stageName: 'Open',
    sourceSlugs: ['website-contact-form', 'linkedin-outreach'],
    notes: '<p>Interested in annual subscription. Requested demo next week.</p>',
  },
  {
    customerName: 'Marcus Webb',
    email: 'marcus.webb@dummy-lead.example',
    subject: 'Pricing for 50-seat plan',
    phone: '+1 555-0102',
    followUpDate: '2026-07-08',
    score: 7,
    quality: 'high',
    pipelineName: 'Sales',
    stageName: 'Sent',
    sourceSlugs: ['google-ads-campaign'],
    notes: '<p>Comparing vendors. Follow up with proposal.</p>',
  },
  {
    customerName: 'Elena Rodriguez',
    email: 'elena.rodriguez@dummy-lead.example',
    subject: 'Marketing automation integration',
    phone: '+1 555-0103',
    followUpDate: '2026-07-20',
    score: 6,
    quality: 'medium',
    pipelineName: 'Marketing',
    stageName: 'Engaged',
    sourceSlugs: ['email-marketing', 'content-marketing'],
    notes: null,
  },
  {
    customerName: 'James Okonkwo',
    email: 'james.okonkwo@dummy-lead.example',
    subject: 'Referral from partner network',
    phone: '+1 555-0104',
    followUpDate: '2026-07-12',
    score: 8,
    quality: 'high',
    pipelineName: 'Sales',
    stageName: 'Revised',
    sourceSlugs: ['partner-referral', 'referral-program'],
    notes: '<p>Warm intro from TechPartners Inc.</p>',
  },
  {
    customerName: 'Priya Sharma',
    email: 'priya.sharma@dummy-lead.example',
    subject: 'Trade show follow-up',
    phone: '+1 555-0105',
    followUpDate: '2026-06-30',
    score: 5,
    quality: 'medium',
    pipelineName: 'Lead Qualification',
    stageName: 'In Review',
    sourceSlugs: ['trade-show-events'],
    notes: '<p>Met at SaaS Summit. Needs qualification call.</p>',
  },
  {
    customerName: 'David Kim',
    email: 'david.kim@dummy-lead.example',
    subject: 'Cold outreach response',
    phone: null,
    followUpDate: '2026-07-05',
    score: 4,
    quality: 'low',
    pipelineName: 'Sales',
    stageName: 'Draft',
    sourceSlugs: ['cold-calling'],
    notes: null,
  },
  {
    customerName: 'Amanda Foster',
    email: 'amanda.foster@dummy-lead.example',
    subject: 'Webinar attendee — product tour',
    phone: '+1 555-0107',
    followUpDate: '2026-07-18',
    score: 7,
    quality: 'medium',
    pipelineName: 'Marketing',
    stageName: 'Qualified',
    sourceSlugs: ['webinar-registration', 'seo-organic-search'],
    notes: '<p>Asked about API access during Q&amp;A.</p>',
  },
  {
    customerName: 'Robert Hayes',
    email: 'robert.hayes@dummy-lead.example',
    subject: 'RFP submission deadline',
    phone: '+1 555-0108',
    followUpDate: '2026-07-02',
    score: 10,
    quality: 'high',
    pipelineName: 'Sales',
    stageName: 'Accepted',
    sourceSlugs: ['industry-publication', 'direct-mail-campaign'],
    notes: '<p>Decision expected by end of month.</p>',
  },
];

module.exports = {
  ACME_DUMMY_LEADS,
};
